### ISSUE TITLE
QR 1 & 2 [Summer 2016]

### ISSUE THREAD

**Issue by shanemcq18** [Foundations-of-Applied-Mathematics/Lab-Development#1241]
These labs are close to being very good. Changes are mostly for clarification.

### QR 1: Decomposition
- [x] _Objective Statement_
- [x] Definition, including full and reduced factorizations
- [x] QR via Gram-Schmidt
    - [x] Modified Gram-Schmidt
    - [x] **Problem 1**: QR via MGS (show them how to check with `scipy.linalg.qr()` and `np.allclose()`)
- [x] Consequences of the QR Decomposition
    - [x] **Problem 2**: Determinant via QR
    - [x] **Problem 3**: Solve A*x* = *b* quickly with back substitution
- [x] QR via Householder
    - [x] Householder Triangularization
    - [x] **Problem 4**: QR via Householder
- [x] Upper Hessenberg Form
    - [x] **Problem 5**: Upper Hessenberg form (show how to check with `scipy.linalg.hessenberg()`)
- Additional Material
    - [x] Complex QR decomposition
    - [x] QR with Pivoting
    - [x] Givens Rotations / Triangularization
        - [x] Modifications for  Hessenberg
- [x] Solutions file
- [x] Spec file
- [x] Test driver
- [x] Proofread

### QR 2: Applications
- [x] _Objective Statement_
- [x] Least Squares
    - [x] **Problem 1**: Solve the normal equation using QR.
    - [x]  Linear least squares set up (delete spring-force example).
    - [x] **Problem 2**: Fit a line to `housing_prices.npy` using your own normal equations solver.
    - [x] _Note_ Linear regression via `scipy.stats.linregress()`
    - [x] **Problem 3**: Fit several polynomials to `housing_prices.npy` (compare answer to `np.polyfit()`).
    - [x] _Warning_ Beware of overfitting. 
    - [x] Circle example.
    - [x] **Problem 4**: Fit an ellipse using `scipy.linalg.lstsq()`
- [x] Computing Eigenvalues
    - [x] **Problem 5**: The Power Method
    - [x] **Problem 6**: QR algorithm (w/ shifts?) and Hessenberg preconditioning
- Additional Material
    - Weighted Least Squares
    - (Simple) Improvements on the QR algorithm
- [x] Solutions file
- [x] Spec file
- [x] Test driver
- [x] Proofread

**Comment by shanemcq18** [comment]
One important [mathematical] change in QR1: the lab used to present the Hessenberg decomposition as `A = Q^T H Q`, but SciPy (and Trefethen) use the convention `A = QHQ^T`. Changing the notation around to match SciPy (`la.hessenberg()`).

**Comment by shanemcq18** [comment]
There are a few least squares tools in Python:
- `numpy.linalg.lstsq()`: General, i.e. solve normal equations.
- `scipy.linalg.lstsq()` General (slightly different than the NumPy one)
- `scipy.optimize.leastsq()`: For functions (curve fitting).
- `numpy.polyfit()`: For polynomials.
- `scipy.stats.linregress()`: For lines.

I think the lab should introduce `scipy.linalg.lstsq()`, `scipy.stats.linregress()`, and `numpy.polyfit()`, probably in that order (`numpy.linalg.lstsq()` isn't really different from the SciPy one, and `scipy.optimize` is covered in Volume 2). Therefore I think there should be a linear regression problem, a polynomial fit problem (that can foreshadow conditioning problems), and then the ellipse problem.

This means this is the place to talk about `numpy.poly1d()` and related functions. This was something that used to be in the NumPy lab, but I think it will fit better here.

Another problem with this: since this is a QR lab, we want them to feel connected to the QR decomposition somehow. The way we've done that in the past is solving the normal equations via QR (i.e., solve _R_ = (_Q_^T)**b**, where _Q_ and _R_ form the reduced QR decomposition of _A_). This problem is essentially identical to "use the QR decomposition to solve the square system Ax = b," which they do in the first QR lab. I guess repetition isn't a bad thing, but it would be nice if there was something . . . more.

**Comment by shanemcq18** [comment]
I'm not super happy with the QR Algorithm that we present in this lab (it doesn't even get all of the right eigenvalues some of the time), but it also doesn't have to be fantastic. We could add shifts without too much trouble, and chasing the bulge could go into additional material. Thoughts, @montu-byu?

**Comment by montu-byu** [comment]
Comments on the QR labs:

1.  The statement as to why we use MGS instead of CGS is actually incorrect.  From Demmel
"Unfortunately, CGS is numerically unstable in floating point arithmetic when the columns of A are nearly linearly dependent. MGS is more stable but may still result in Q being far from orthogonal  when A is ill-conditioned."

As it turns out Householder is even more numerically stable.

2.  Even as a side remark I don't think we should be asking students questions like "Can you prove it?"  These should be saved for the text.

3. I'm okay with adding QR with pivoting, but this sentence "The QR factorization with pivoting is the basis for several rank-revealing algorithms and for handling rank-deficient least matrices problems (solving Ax = b where A is m × n with m < n)." is confusing and talks about things they likely do not know (like rank revealing).  Clearly you have taken 510.... Actually on second thought maybe we should not say anything about QR with pivoting.

4. QR1 seems very "theory dense" in the explanations.

5. Simple typo in QR2 "Perron-Frobenius theoremguarantees"

6.  You could add shifts without too much trouble (for the students) but it will make an already long lab even longer.  There are tons of algorithms you could add in the additional material but I think it mostly would be overkill unless there is something specific that Jeff or Tyler want to see. The coolest algorithms would be lost on first semester ACME students...

**Comment by shanemcq18** [comment]
- Made a few small adjustments to the CGS / MGS explanation so that it is correct
- Removed "(Can you prove it?)" twice
- Removed the QR with pivoting follow up (the part about rank-revealing stuff), but left in the "how to" with SciPy
- Fixed "theoremguarantees" typo, along with few other typos
- Shifts will go in additional material, but nothing more. Will work on this a little later.

I couldn't figure out how to slim down the theory of Householder in QR 1 to less than 2 pages, but (in my opinion) it's a little more readable now than it was before. It also matches the way that the textbook presents it.

Last thing @montu-byu: what chapter in Volume 1 deals with the power method?

**Comment by shanemcq18** [comment]
I was hoping to get this done, but the Additional Material section isn't quite ready (which isn't a big deal right now). Some things to think about the next time we look over this:
- Make sure the reference to the proof of the power method is correct.
- A note/demonstration about how crazy fast the power method converges?
- Review the QR algorithm section again. Use shifts? Put shifts in additional material?
- WLS in additional material
- OLS with other norms in additional material (and find out where that mystery figure came from)
